### ISSUE TITLE
yarn buildを実行するとエラーが発生

### ISSUE THREAD

**Issue by kryota-dev** [ryota-k0827/github-labels-export-import-web#1]
## 概要
`yarn build`を実行すると、以下のようなエラーが発生した。

```bash
[vite]: Rollup failed to resolve import "global" from "node_modules/@emotion/react/dist/emotion-react.browser.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "global" from "node_modules/@emotion/react/dist/emotion-react.browser.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///Users/ryota/work/github/github-labels-export-import-web/node_modules/vite/dist/node/chunks/dep-db16f19c.js:45916:19)
    at onwarn (file:///Users/ryota/work/github/github-labels-export-import-web/node_modules/vite/dist/node/chunks/dep-db16f19c.js:45714:13)
    at Object.onwarn (file:///Users/ryota/work/github/github-labels-export-import-web/node_modules/rollup/dist/es/shared/rollup.js:23225:13)
    at ModuleLoader.handleResolveId (file:///Users/ryota/work/github/github-labels-export-import-web/node_modules/rollup/dist/es/shared/rollup.js:22352:26)
    at file:///Users/ryota/work/github/github-labels-export-import-web/node_modules/rollup/dist/es/shared/rollup.js:22313:26
error Command failed with exit code 1.
```

おそらく、nodeのコアモジュールをポリフィルしたことが原因。
https://github.com/ryota-k0827/github-labels-export-import-web/blob/main/vite.config.ts#L9-L11

## タスク
- [ ] `yarn build`が正常に動作するように解決する。

## 参考になりそうな記事
- https://zenn.dev/kra8/articles/c9ed05abb90d60
- https://socket.dev/npm/package/vite-plugin-node-polyfills

**Comment by kryota-dev** [comment]
`yarn upgrade --latest`を叩いてパッケージのバージョンアップしたらビルドできたので、一旦このissueについてはcloseとする。
